name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: |
        cd client
        npm install
        cd ../server
        npm install
        
    - name: Run Frontend Tests
      run: |
        cd client
        npm run test
        
    - name: Run Backend Tests
      run: |
        cd server
        npm run test
        
    - name: Build Frontend
      run: |
        cd client
        npm run build 